version: 2
jobs:
  set-workspace:
    docker:
      - image: circleci/python:2.7
    working_directory: ~/samba-chassis
    steps:
      - checkout
      - attach_workspace:
          at: ~/samba-chassis
      - persist_to_workspace:
          root: .
          paths: .
  python-unit-test:
    docker:
      - image: circleci/python:2.7
    working_directory: ~/samba-chassis/python
    steps:
      - attach_workspace:
          at: ~/samba-chassis
      - run:
          name: Installing dependencies
          command: |
            sudo pip install pipenv
            pipenv install -d
            pipenv run pytest tests/unit
      - persist_to_workspace:
          root: .
          paths: .
  sonar-analysis:
    docker:
      - image: circleci/openjdk:8-jdk-browsers
    working_directory: ~/samba-chassis
    steps:
      - attach_workspace:
          at: ~/samba-chassis
      - run:
          name: Sonar analysis
          command: |
            curl --header "Authorization:token $GITHUB_USER_TOKEN" --header "Accept:application/vnd.github.v3.raw" --remote-name --location https://raw.githubusercontent.com/sambatech/devops/master/circle-ci/run-sonar.sh
            chmod a+x run-sonar.sh
            ./run-sonar.sh install
            ./run-sonar.sh run
            rm -rf test-reports
workflows:
  version: 2
  main-pipeline:
    jobs:
      - set-workspace
      - python-unit-test:
          requires:
            - set-workspace
      - sonar-analysis:
          requires:
            - python-unit-test